server:
  port: 8080

spring:
  application:
    name: orderflow

  datasource:
    url: jdbc:mysql://localhost:3307/orderflow
    username: orderflow
    password: orderflow
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  metrics:
    enable:
      all: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs